#!/usr/bin/env python3
"""Write a module `symbols.txt` from an RSO's export table, and report the import resolution.

The export table is the only symbol information a retail RSO carries: name, section index, section
offset and a name hash - no sizes and no local symbols. So the generated `symbols.txt` is a *seed*:
it pins the names and addresses the original link exported, and the analyzer fills in the rest once a
module can be split (see docs/rso-modules.md for the splitter blocker).

Section names are derived from evidence, and the derivation is recorded per section:

    proven    .init   the section holding the module's prolog entry point
              .ctors  the section holding the `_ctors` label
              .dtors  the section holding the `_dtors` label
              .bss    the section with no file bytes whose size equals the header's bss size
    inferred  everything else, by index order from the conventional REL section pool

Usage:
    python tools/rso/symbols.py --all [--out config/RMHE08] [--report build/tmp/rso-symbols/summary.md]
    python tools/rso/symbols.py --rso <file.rso> --print
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # tools/
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import inventory
import unitutil as uu

# Fallback order for sections the evidence cannot name: small export-less sections first (extab /
# extabindex are small and never carry exports), then the data sections.
FALLBACK = ["extab", "extabindex", ".sdata", ".sbss", ".sdata2", ".sbss2", ".text", ".rodata", ".data"]
DATA_HINT = re.compile(r"_data$|table|@LOCAL@|String|string", re.I)

FUNC_HINT = re.compile(r"__F|^_prolog$|^_epilog$|^_unresolved$|^__register_|^__destroy_|^__init_")


def section_names(mod):
    """{section index: (name, how)} - how is 'proven' or 'inferred'."""
    names, used = {}, set()

    def take(idx, name, how):
        names[idx] = (name, how)
        used.add(name)

    take(mod["prolog_section"], ".init", "proven")
    for idx in range(len(mod["sections"])):
        exports = [e["name"] for e in mod["exports"] if e["section"] == idx]
        if any(n == "_ctors" or n.startswith("_ctors$") for n in exports):
            take(idx, ".ctors", "proven")
        if any(n == "_dtors" or n.startswith("_dtors$") for n in exports):
            take(idx, ".dtors", "proven")
    for s in mod["sections"]:
        if s["index"] and not s["in_file"] and s["size"] == mod["bss_size"] and s["size"]:
            take(s["index"], ".bss", "proven")
            break
    # Sections whose exports look like data are named by that evidence first (const-looking names get
    # .rodata, plain `_data` names get .data); the rest fall back to the conventional pool.
    pool = [n for n in FALLBACK if n not in used]
    leftover = [s for s in mod["sections"] if s["index"] and s["index"] not in names and s["size"]]
    for s in leftover:
        exports = [e["name"] for e in mod["exports"] if e["section"] == s["index"]]
        if not any(DATA_HINT.search(n) for n in exports):
            continue
        const = all("_data" not in n for n in exports)
        name = ".rodata" if const else ".data"
        if name in used:
            name = ".rodata" if name == ".data" else ".data"
        if name not in used:
            take(s["index"], name, "inferred")
    for s in leftover:
        if s["index"] in names:
            continue
        take(s["index"], pool.pop(0) if pool else ".section_%d" % s["index"], "inferred")
    return names


def symbol_type(name, section):
    """Labels inside .ctors/.dtors are list slots, not functions."""
    if section in (".ctors", ".dtors"):
        return "label"
    return "function" if FUNC_HINT.search(name) else "object"


def emit(mod, out_dir):
    names = section_names(mod)
    module = os.path.splitext(os.path.basename(mod["path"]))[0]
    lines = ["// Generated by tools/rso/symbols.py from the RSO export table - names and section-relative",
             "// addresses are exact; sizes and local symbols are unknown (the analyzer fills them in).",
             "// Section names: " + ", ".join("%d=%s(%s)" % (i, n, how)
                                             for i, (n, how) in sorted(names.items()))]
    exports = sorted(mod["exports"], key=lambda e: (e["section"], e["offset"]))
    seen = {}
    dupes = []
    for e in exports:
        if e["section"] not in names:
            continue
        sec = names[e["section"]][0]
        name = e["name"]
        if name in seen:
            seen[name] += 1
            dupes.append("%s@%s:0x%X" % (name, sec, e["offset"]))
            name = "%s$%d" % (name, seen[name])
        else:
            seen[name] = 1
        lines.append("%s = %s:0x%X; // type:%s scope:global" % (name, sec, e["offset"],
                                                                symbol_type(e["name"], sec)))
    if dupes:
        lines.append("// duplicate export names given a $N suffix: " + ", ".join(dupes))
    path = os.path.join(out_dir, module, "symbols.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    return path, len(exports), names


def dol_symbols():
    """{name: line} for the DOL's symbols.txt - read with a stream, never loaded into a prompt."""
    path = os.path.join(uu.ROOT, "config", "RMHE08", "symbols.txt")
    out = {}
    if not os.path.exists(path):
        return out
    for line in open(path, encoding="utf-8", errors="replace"):
        if " = " in line:
            out[line.split(" = ", 1)[0].strip()] = line.strip()
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir", default=os.path.join(uu.ROOT, "orig", "RMHE08", "files"))
    ap.add_argument("--rso", action="append", default=[])
    ap.add_argument("--all", action="store_true", help="every *.rso under --dir")
    ap.add_argument("--out", default=os.path.join(uu.ROOT, "config", "RMHE08"),
                    help="root to write <module>/symbols.txt under")
    ap.add_argument("--report", help="write the section/import report here")
    ap.add_argument("--print", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    paths = list(args.rso)
    if args.all or not paths:
        for root, _d, files in os.walk(args.dir):
            paths += [os.path.join(root, f) for f in sorted(files) if f.lower().endswith(".rso")]
    mods = [m for m in (inventory.parse(p) for p in sorted(paths)) if m]
    if not mods:
        raise SystemExit("no RSO files found")

    dol = dol_symbols()
    module_exports = {os.path.splitext(os.path.basename(m["path"]))[0]: {e["name"] for e in m["exports"]}
                      for m in mods}
    report = ["# RSO symbol map", "",
              "Generated by `tools/rso/symbols.py`. Section names marked *proven* come from the prolog",
              "pointer, the `_ctors`/`_dtors` labels or the bss size; the rest are inferred by index",
              "order and need confirming when a module can be split (`docs/rso-modules.md`).", ""]

    for m in sorted(mods, key=lambda m: -m["size"]):
        module = os.path.splitext(os.path.basename(m["path"]))[0]
        path, count, names = emit(m, args.out)
        print("%-18s %3d exports -> %s" % (module, count, os.path.relpath(path, uu.ROOT)))
        report.append("## %s (%s)" % (module, m["name"]))
        report.append("")
        report.append("| section | name | how | size |")
        report.append("| --- | --- | --- | --- |")
        for s in m["sections"]:
            if s["index"] == 0 or (s["size"] == 0 and s["index"] not in names):
                continue
            name, how = names.get(s["index"], ("(unnamed)", "-"))
            report.append("| %d | `%s` | %s | 0x%X |" % (s["index"], name, how, s["size"]))
        resolved, unknown = [], []
        for imp in m["imports"]:
            provider = "DOL" if imp["name"] in dol else next(
                (mo for mo, exps in module_exports.items() if mo != module and imp["name"] in exps), None)
            (resolved if provider else unknown).append((imp["name"], provider or "unresolved"))
        report.append("")
        providers = {}
        for _n, prov in resolved:
            providers[prov] = providers.get(prov, 0) + 1
        report.append("%d exports, %d imports (%d resolved, %d unresolved)." % (
            len(m["exports"]), len(m["imports"]), len(resolved), len(unknown)))
        report.append("")
        report.append("Providers: " + ", ".join("%s=%d" % (k, v) for k, v in
                                                sorted(providers.items(), key=lambda x: -x[1])))
        if resolved:
            report.append("")
            report.append("Resolved imports: " + ", ".join("`%s` (%s)" % (n, p) for n, p in resolved[:40]))
        if unknown:
            report.append("")
            report.append("Unresolved imports: " + ", ".join("`%s`" % n for n, _ in unknown[:40]))
        report.append("")

    if args.report:
        os.makedirs(os.path.dirname(args.report), exist_ok=True)
        open(args.report, "w", encoding="utf-8", newline="\n").write("\n".join(report))
        print("wrote", os.path.relpath(args.report, uu.ROOT))


if __name__ == "__main__":
    main()
