"""The gate's table on the `test_gate_golden` scenarios, recorded from the monolithic `land.py` (main at ec8223e66)
before the WP4 split: `{scenario: {"exit": code, "rows": [[name, status, kind], ...]}}`. Data, not a test."""
GOLDEN = {
 "noop-dry-run": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["orchestrator-only batch (no worker outboxes to check)", "PASS", "gate"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"]]},
 "noop": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["orchestrator-only batch (no worker outboxes to check)", "PASS", "gate"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "PASS", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "PASS", "gate"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "PASS", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "PASS", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "PASS", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "PASS", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim released: CLAUDE.md", "PASS", "bookkeeping"]]},
 "unit-dry-run": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"]]},
 "unit": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "PASS", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "PASS", "gate"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "PASS", "gate"],
   ["no batch unit's target object references data no claim covers (unowned data stays behind)", "PASS", "gate"],
   ["no batch unit the batch really changes still has data only it references left unclaimed (touched = registered, recut or compiled object changed)", "PASS", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "PASS", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "PASS", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "PASS", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim released: Net/net_new", "PASS", "bookkeeping"]]},
 "unit-no-selftests": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "PASS", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "PASS", "gate"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "PASS", "gate"],
   ["no batch unit's target object references data no claim covers (unowned data stays behind)", "PASS", "gate"],
   ["no batch unit the batch really changes still has data only it references left unclaimed (touched = registered, recut or compiled object changed)", "PASS", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "PASS", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "PASS", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "PASS", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim released: Net/net_new", "PASS", "bookkeeping"]]},
 "two-units-outbox-refusal": {"exit": 1, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "FAIL", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"]]},
 "two-units-neighbour-moved-regressed": {"exit": 1, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["orchestrator-only batch (no worker outboxes to check)", "PASS", "gate"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "PASS", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "PASS", "gate"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "PASS", "gate"],
   ["no batch unit's target object references data no claim covers (unowned data stays behind)", "PASS", "gate"],
   ["no batch unit the batch really changes still has data only it references left unclaimed (touched = registered, recut or compiled object changed)", "PASS", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "FAIL", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "PASS", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "FAIL", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim release deferred", "PASS", "gate"]]},
 "tools": {"exit": 0, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["orchestrator-only batch (no worker outboxes to check)", "PASS", "gate"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "PASS", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "PASS", "gate"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "PASS", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "PASS", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "PASS", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "PASS", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim released: tools/units/fixture_tool.py", "PASS", "bookkeeping"]]},
 "lint-refusal": {"exit": 1, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "FAIL", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"]]},
 "no-base-dry-run": {"exit": 1, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["batch base recorded", "FAIL", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"]]},
 "unit-object-rows-refuse": {"exit": 1, "rows": [
   ["ground truth (build.sha1 == the DOL's hash)", "PASS", "gate"],
   ["main has not moved since the batch base", "PASS", "bookkeeping"],
   ["every changed path belongs to a batch", "PASS", "gate"],
   ["no batch file carries a git conflict marker", "PASS", "gate"],
   ["every unit's outbox validates (warning)", "PASS", "bookkeeping"],
   ["every unit's branch carries its work as commits", "PASS", "bookkeeping"],
   ["style lint (§6.5) adds no violation", "PASS", "gate"],
   ["all tool selftests pass (except the parked list)", "PASS", "gate"],
   ["rule 2 registration boundary (warning)", "PASS", "gate"],
   ["the gate's own subject follows the convention", "PASS", "gate"],
   ["configure.py (exit 0)", "PASS", "gate"],
   ["split (config.json) (exit 0)", "PASS", "gate"],
   ["configure.py (after the split) (exit 0)", "PASS", "gate"],
   ["every batch unit is registered (configure.py + splits.txt + build graph)", "FAIL", "gate"],
   ["every batch unit compiles (compile gate)", "PASS", "gate"],
   ["every batch unit's relocations resolve against the link (no new undefined reference)", "FAIL", "gate"],
   ["the batch base carries an unresolved-reference snapshot for every unit", "FAIL", "bookkeeping"],
   ["ninja (exit 0)", "PASS", "gate"],
   ["report.json (exit 0)", "PASS", "gate"],
   ["rule 10 (vtable ownership) adds no violation", "FAIL", "gate"],
   ["the batch base carries a data-closure snapshot", "FAIL", "bookkeeping"],
   ["no batch unit's target object references data no claim covers (unowned data stays behind)", "FAIL", "gate"],
   ["no batch unit the batch really changes still has data only it references left unclaimed (touched = registered, recut or compiled object changed)", "FAIL", "gate"],
   ["no unit's split target object moved under the batch (a neighbour re-ranged)", "PASS", "gate"],
   ["per-symbol re-measure reproduces the report from the objects", "FAIL", "gate"],
   ["ninja changes (DOL-level totals, informational) (exit 0)", "PASS", "gate"],
   ["no symbol or unit regressed", "PASS", "gate"],
   ["every --allow-regression was actually needed (warning)", "PASS", "bookkeeping"],
   ["ok (main.dol verified) (exit 0)", "PASS", "gate"],
   ["ok was recreated by THIS run", "PASS", "gate"],
   ["ninja baseline (exit 0)", "PASS", "gate"],
   ["claim release deferred", "PASS", "gate"]]}}
