#!/usr/bin/env python3
"""sync_playbook_index.py - generate docs/matching/index.md from the front matter of docs/matching/NNN-slug.md.

The matching playbook is one file per idea, `docs/matching/NNN-slug.md` (three-digit zero-padded, permanent id +
a short slug), each opening with a front-matter block:

    ---
    id: 43
    title: <the idea's title>
    status: works            # works | ruled-out | todo | superseded
    problem: <the Problem sentence, single line>
    tags: [flags, source-shape]
    applies: []              # compiler versions/libs it is known to apply to, e.g. [Wii/1.3]
    demo:                    # NNN-slug.cpp when a compilable demonstration exists
    ---

`docs/matching/index.md` is GENERATED from those blocks (id, title, status, tags, problem; sorted by id, the
problem capped at 220 characters). The tool refuses loudly - and writes nothing - on a duplicate id, a missing or
malformed key, an unknown tag or status, a file name whose id/slug disagrees with its front matter, and a `demo`
that names a missing file. Ids are permanent: 600+ citations of "playbook N" / "row N" exist in the tree.

    python tools/agents/sync_playbook_index.py             # write docs/matching/index.md
    python tools/agents/sync_playbook_index.py --check     # exit 1 when index.md is stale; write nothing
    python tools/agents/sync_playbook_index.py --print     # print the generated index
    python tools/agents/sync_playbook_index.py --where N   # print idea N's path (exit 1 when unknown)
    python tools/agents/sync_playbook_index.py --json      # the parsed index as JSON
    python tools/agents/sync_playbook_index.py --selftest  # fixtures: duplicates, bad keys, slug mismatch, ...
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

DIR_REL = "docs/matching"
TARGET_REL = DIR_REL + "/index.md"
TARGET_NAME = TARGET_REL

TAGS = ("flags", "pragma", "source-shape", "allocator", "data", "vtable", "linker", "sections", "symbols",
        "relocations", "measurement", "process", "tooling")
STATUSES = ("works", "ruled-out", "todo", "superseded")
KEYS = ("id", "title", "status", "problem", "tags", "applies", "demo")
# Optional keys (a stage-4 review sets them; absent means unreviewed / no relations):
#   reviewed: YYYY-MM-DD   the date the idea was verified and refined
#   related: [ids]         ideas a reader should also open
#   superseded_by: N       the idea that replaces this one (status superseded)
OPTIONAL_KEYS = ("reviewed", "related", "superseded_by")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
FILE_RE = re.compile(r"^(\d{3})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$")
# The problem sentence in both house styles: the current `**Problem.**` and the older `Problem:`.
PROBLEM_RES = (re.compile(r"^\*\*Problem\.\*\*\s*(.*)$"), re.compile(r"^Problem:\s*(.*)$"))

CELL_CAP = 220
NL = chr(10)
BS = chr(92)  # a literal backslash, built rather than written so no escape can be mangled in transit

BEGIN = ("<!-- GENERATED by tools/agents/sync_playbook_index.py from the front matter of docs/matching/NNN-*.md; "
         "do not edit by hand -->")

LEAD = [
    "# Matching playbook - index",
    "",
    "Every idea has one file, `NNN-slug.md`, and the **id is permanent** (`python tools/agents/ideas.py where N` "
    "prints the path, `ideas.py find <words>` searches). The idea column links to it, `status` is "
    "`works | ruled-out | todo | superseded` (one table per status),",
    "`tags` come from the fixed vocabulary in [README.md](README.md), and the problem column is the opening of the "
    "idea's own problem sentence, truncated at %d characters." % CELL_CAP,
]


def read(path):
    """Read a repository text file newline-preserving."""
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def find_root(start=None):
    """Walk up from `start` (default: this file) to the directory holding configure.py."""
    cur = os.path.abspath(start or HERE)
    while True:
        if os.path.isfile(os.path.join(cur, "configure.py")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            raise SystemExit("refusing: no configure.py above %s" % (start or HERE))
        cur = parent


def problem_sentence(body):
    """The section's problem paragraph (list of lines), first line onwards until a blank line, or None."""
    for i, line in enumerate(body):
        for rx in PROBLEM_RES:
            m = rx.match(line)
            if not m:
                continue
            paras = [m.group(1).strip()]
            for cont in body[i + 1:]:
                if not cont.strip():
                    break
                paras.append(cont.strip())
            return " ".join(paras)
    return None


def cell(text, cap=CELL_CAP, sentence=False):
    """One markdown table cell: single-line, `|` escaped, capped at a word boundary."""
    t = " ".join(text.split()).replace("|", BS + "|")
    if sentence and t and (t[0].isalpha() and t[0].islower()):
        t = t[0].upper() + t[1:]
    if cap and len(t) > cap:
        t = t[:cap].rsplit(" ", 1)[0] + "..."
    return t


# ---- front matter --------------------------------------------------------------------------------------------

def parse_front_matter(text):
    """({key: raw string value}, body text after the block) or raises ValueError naming the defect.

    A deliberately tiny parser (`key: value` lines between two `---` lines, LF or CRLF): the values are read
    raw so a problem sentence containing `:` or quotes needs no escaping.
    """
    lines = text.split("\n")
    if not lines or lines[0].rstrip("\r") != "---":
        raise ValueError("no front matter: the file must open with a `---` line")
    fm = {}
    for i in range(1, len(lines)):
        line = lines[i].rstrip("\r")
        if line == "---":
            return fm, "\n".join(lines[i + 1:])
        m = re.match(r"^([a-z_]+):(?:\s(.*))?$", line)
        if not m:
            raise ValueError("malformed front-matter line %d: %r" % (i + 1, line[:60]))
        if m.group(1) in fm:
            raise ValueError("front-matter key `%s` appears twice" % m.group(1))
        fm[m.group(1)] = (m.group(2) or "").strip()
    raise ValueError("front matter is never closed (no second `---` line)")


def parse_list(raw):
    """`[a, b]` -> ['a', 'b'] (whitespace-trimmed; `[]` -> []); None when the value is not a bracket list."""
    raw = raw.strip()
    if not (raw.startswith("[") and raw.endswith("]")):
        return None
    inner = raw[1:-1].strip()
    return [x.strip() for x in inner.split(",")] if inner else []


def load_idea(path, name):
    """(idea dict, [defects]) for one NNN-slug.md."""
    defects = []
    m = FILE_RE.match(name)
    if not m:
        return None, ["%s: file name is not `NNN-slug.md` (three digits, lowercase slug)" % name]
    fid, slug = int(m.group(1)), m.group(2)
    try:
        fm, _body = parse_front_matter(read(path))
    except ValueError as e:
        return None, ["%s: %s" % (name, e)]
    for k in KEYS:
        if k not in fm:
            defects.append("%s: front-matter key `%s` is missing" % (name, k))
    for k in fm:
        if k not in KEYS and k not in OPTIONAL_KEYS:
            defects.append("%s: unknown front-matter key `%s`" % (name, k))
    if defects:
        return None, defects
    idea = {"file": name, "slug": slug, "title": fm["title"], "status": fm["status"], "problem": fm["problem"],
            "demo": fm["demo"]}
    if not re.match(r"^\d+$", fm["id"]):
        defects.append("%s: id `%s` is not an integer" % (name, fm["id"]))
    else:
        idea["id"] = int(fm["id"])
        if idea["id"] != fid:
            defects.append("%s: file name id %03d does not match front-matter id %d" % (name, fid, idea["id"]))
    if not fm["title"]:
        defects.append("%s: empty title" % name)
    if not fm["problem"]:
        defects.append("%s: empty problem" % name)
    if fm["status"] not in STATUSES:
        defects.append("%s: status `%s` is not one of %s" % (name, fm["status"], "/".join(STATUSES)))
    tags = parse_list(fm["tags"])
    if tags is None:
        defects.append("%s: tags must be a bracket list, e.g. [flags, pragma]" % name)
        tags = []
    for t in tags:
        if t not in TAGS:
            defects.append("%s: unknown tag `%s` (vocabulary: %s)" % (name, t, ", ".join(TAGS)))
    idea["tags"] = tags
    applies = parse_list(fm["applies"])
    if applies is None:
        defects.append("%s: applies must be a bracket list, e.g. [Wii/1.3] or []" % name)
        applies = []
    idea["applies"] = applies
    reviewed = fm.get("reviewed", "")
    if reviewed and not DATE_RE.match(reviewed):
        defects.append("%s: reviewed `%s` is not a YYYY-MM-DD date" % (name, reviewed))
    idea["reviewed"] = reviewed
    related = parse_list(fm.get("related", "[]"))
    if related is None or not all(re.match(r"^\d+$", x) for x in related):
        defects.append("%s: related must be a bracket list of idea ids, e.g. [43, 44] or []" % name)
        related = []
    idea["related"] = [int(x) for x in related]
    sup = fm.get("superseded_by", "")
    if sup and not re.match(r"^\d+$", sup):
        defects.append("%s: superseded_by `%s` is not an idea id" % (name, sup))
        sup = ""
    idea["superseded_by"] = int(sup) if sup else None
    if fm["demo"]:
        if os.path.basename(fm["demo"]) != fm["demo"] or not fm["demo"].startswith("%03d-" % fid):
            defects.append("%s: demo `%s` must be a `%03d-*` file beside the idea" % (name, fm["demo"], fid))
        elif not os.path.isfile(os.path.join(os.path.dirname(path), fm["demo"])):
            defects.append("%s: demo names a missing file `%s`" % (name, fm["demo"]))
    return (idea if not defects else None), defects


def load_ideas(root):
    """([ideas sorted by id], [defects]) over docs/matching/NNN-*.md."""
    d = os.path.join(root, *DIR_REL.split("/"))
    ideas, defects = [], []
    if not os.path.isdir(d):
        return [], ["%s does not exist" % DIR_REL]
    for name in sorted(os.listdir(d)):
        if not (name.endswith(".md") and name[:1].isdigit()):
            continue
        idea, dd = load_idea(os.path.join(d, name), name)
        defects.extend(dd)
        if idea:
            ideas.append(idea)
    seen = {}
    for i in ideas:
        seen.setdefault(i["id"], []).append(i["file"])
    for n in sorted(seen):
        if len(seen[n]) > 1:
            defects.append("id %d appears %d times (%s)" % (n, len(seen[n]), ", ".join(seen[n])))
    ids = {i["id"] for i in ideas}
    for i in ideas:
        for r in i["related"]:
            if r not in ids or r == i["id"]:
                defects.append("%s: related id %d is not another existing idea" % (i["file"], r))
        sup = i["superseded_by"]
        if sup is not None and (sup not in ids or sup == i["id"]):
            defects.append("%s: superseded_by %d is not another existing idea" % (i["file"], sup))
        if i["status"] == "superseded" and sup is None:
            defects.append("%s: status superseded needs `superseded_by: N`" % i["file"])
    if not ideas and not defects:
        defects.append("no NNN-slug.md idea file was found in %s" % DIR_REL)
    return sorted(ideas, key=lambda i: (i["id"], i["file"])), defects


SECTIONS = (("works", "Ideas that work"),
            ("ruled-out", "Ruled out - tried and it did not work, do not re-run"),
            ("todo", "Not tried yet"),
            ("superseded", "Superseded"))


def build_index(ideas):
    """The whole index.md: one table per status (empty statuses are omitted), each sorted by id."""
    lines = [BEGIN, ""] + list(LEAD)
    for status, heading in SECTIONS:
        rows = [i for i in ideas if i["status"] == status]
        if not rows:
            continue
        lines += ["", "## %s (%d)" % (heading, len(rows)), "", "| # | idea | status | tags | problem |",
                  "| --- | --- | --- | --- | --- |"]
        for i in rows:
            lines.append("| %d | [%s](%s) | %s | %s | %s |"
                         % (i["id"], cell(i["title"], cap=None), i["file"], i["status"], ", ".join(i["tags"]),
                            cell(i["problem"], sentence=True)))
    return NL.join(lines) + NL


# ---- tag suggestion (used by `ideas.py new` and tools/units/playbook.py drafts) ------------------------------
MAX_TAGS = 4
TAG_KEYWORDS = {
    "flags": ["flag", "-opt", "-o4", "-o3", "cflags", "-pool", "-str ", "-fp_contract", "-inline", "-func_align",
              "-sdata", "-cpp_exceptions", "mw_version"],
    "pragma": ["pragma"],
    "source-shape": ["source shape", "rewrite", "loop shape", "polarity", "declaration order", "temporar",
                     "switch", "ternary", "operand order", "declared shape", "cast", "source spelling", "`new`"],
    "allocator": ["allocator", "register", "colour", "color", "web priority", "live range"],
    "data": [".data", ".sdata", ".sbss", ".bss", ".rodata", "literal pool", "string pool", "jump table",
             "data range", "data claim", "pool entry", "string literal", "unknown-size"],
    "vtable": ["vtable", "virtual", "class hierarchy", "key function", "vptr", "polymorphic"],
    "linker": ["linker", "ctors", "dtors", "link padding", "ldscript", "flipped", "flip "],
    "sections": ["section", "extab", "splits.txt", "claim"],
    "symbols": ["symbol", "mangl", "name ", "names ", "naming"],
    "relocations": ["reloc"],
    "measurement": ["measure", "metric", "objdiff", "percent", "score", "stale object", "instrument",
                    "first divergence", "match_percent", "divergence"],
    "process": ["lane", "merge", "merging", "record", "deferred", "tiling", "campaign", "one owner"],
    "tooling": ["tool", "script", "automate", "harness", "generate, compile"],
}


def derive_tags(title, problem):
    """A crude keyword suggestion (at most MAX_TAGS, ranked by hit count) - a human refines it by editing."""
    text = (title + " " + problem).lower()
    hits = []
    for tag, kws in TAG_KEYWORDS.items():
        n = sum(text.count(k) for k in kws)
        if n:
            hits.append((-n, TAGS.index(tag), tag))
    return [t for _n, _o, t in sorted(hits)[:MAX_TAGS]]


def cmd_sync(a):
    root = find_root(a.repo)
    ideas, defects = load_ideas(root)
    if defects:
        for d in defects:
            print("refusing: %s" % d, file=sys.stderr)
        return 1
    if getattr(a, "where", None) is not None:
        for i in ideas:
            if i["id"] == a.where:
                print("%s/%s" % (DIR_REL, i["file"]))
                return 0
        print("no idea %d in %s (ids: %d-%d)" % (a.where, DIR_REL, ideas[0]["id"], ideas[-1]["id"]), file=sys.stderr)
        return 1
    if getattr(a, "json", False):
        json.dump(ideas, sys.stdout, indent=1, sort_keys=True)
        sys.stdout.write("\n")
        return 0
    block = build_index(ideas)
    target_path = os.path.join(root, *TARGET_REL.split("/"))
    if a.print_block:
        sys.stdout.write(block)
        return 0
    old = read(target_path) if os.path.isfile(target_path) else None
    if a.check:
        if old != block:
            print("stale: %s differs from the front matter of %s/*.md (%d ideas) - run "
                  "python tools/agents/sync_playbook_index.py" % (TARGET_NAME, DIR_REL, len(ideas)), file=sys.stderr)
            return 1
        print("%s is in sync with %s/*.md (%d ideas, ids %d-%d)"
              % (TARGET_NAME, DIR_REL, len(ideas), ideas[0]["id"], ideas[-1]["id"]))
        return 0
    if old == block:
        print("%s: in sync" % TARGET_NAME)
        return 0
    write(target_path, block)
    print("updated %s (%d ideas, ids %d-%d)" % (TARGET_NAME, len(ideas), ideas[0]["id"], ideas[-1]["id"]))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 when the index is stale")
    ap.add_argument("--print", dest="print_block", action="store_true", help="print the generated index")
    ap.add_argument("--where", type=int, metavar="N", help="print idea N's path; exit 1 when unknown")
    ap.add_argument("--json", action="store_true", help="print the parsed index as JSON")
    ap.add_argument("--repo", help="repository root (default: walk up for configure.py)")
    ap.add_argument("--selftest", action="store_true", help="run tools/agents/sync_playbook_index_selftest.py")
    a = ap.parse_args()
    if a.selftest:
        import subprocess
        return subprocess.call([sys.executable, os.path.join(HERE, "sync_playbook_index_selftest.py")])
    return cmd_sync(a)


if __name__ == "__main__":
    sys.exit(main())
